version: 0.1.0   

name: voting-app-react
description: 'The Stack provides all boilerplate app and deployment code of the voting application'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:

  - name: AZURE_CREDENTIALS
    description: Enter the azure login token. The tokes is based on Azure service principal. Read readme.md to discover about generating the token using Azure CLI.
    is-secret: true
    required: true
  
  - name: AZURE_AKS_RESOURCE_GROUP
    description: Enter the AKS resource group in which this cluster is created.
    is-secret: true
    required: true

  - name: AZURE_AKS_NAME
    description: Enter the AKS service name.
    is-secret: true
    required: true

  - name: AKS_KUBECONFIG
    description: Enter the kubeconfig JSON token. Read readme.md to discover how to generate this token using CLI
    is-secret: true
    required: true

  - name: MONGODB_CONNECTION_STRING
    description: Enter the hosted Mongo Db connection string.
    is-secret: true
    required: true

configs:
   repo-metadata:
      parameters:
        description: 'Azure service principal'
        secrets: 
          - name: AZURE_CREDENTIALS
            value: ${{inputs.AZURE_CREDENTIALS}}

          - name: AZURE_AKS_RESOURCE_GROUP
            value: ${{inputs.AZURE_AKS_RESOURCE_GROUP}}

          - name: AZURE_AKS_NAME
            value: ${{inputs.AZURE_AKS_NAME}}

          - name: AKS_KUBECONFIG
            value: ${{inputs.AKS_KUBECONFIG}}

          - name: MONGODB_CONNECTION_STRING
            value: ${{inputs.MONGODB_CONNECTION_STRING}}
        topics:
        - react
        - reactjs
        - voting-app
        - azure
        - azure-static-app
        - azure-react-app
        
   environments:                                        
    - name: development
      parameters: 
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*
