apiVersion : apps/v1
kind: Deployment
metadata:
  name: "backend-go-voting"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "backend-go-voting"
  template:
    metadata:
      labels:
        app: "backend-go-voting"
    spec:
      containers:
        - name: "backend-go-voting"
          # name doesnt matter since we will replace it with image substitution in actions
          image: "srahul3.azurecr.io/backend-go-voting"
          ports:
            - containerPort: 8080
          env:            
            - name: MONGODB_CONNECTION_STRING
              valueFrom: 
                secretKeyRef:
                  # az secret key-val vault name
                  name: k8s-secret 
                  # key with the given vault
                  key: MONGODB_CONNECTION_STRING 

