apiVersion : apps/v1
kind: Deployment
metadata:
  name: "srahul3githubaks-261c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "srahul3githubaks-261c"
  template:
    metadata:
      labels:
        app: "srahul3githubaks-261c"
    spec:
      containers:
        - name: "srahul3githubaks-261c"
          image: "srahul3.azurecr.io/srahul3githubaks"
          ports:
            - containerPort: 8080
          env:
            - name: TEST
              value: X
            - name: TEST2
              valueFrom: 
                secretKeyRef:
                  # az secrest key-val vault name
                  name: k8s-secret 
                  # key with the given vault
                  key: k8ssecret 
