apiVersion: v1
kind: Service
metadata:
    name: "backend-go-voting"
    labels:
        app: "backend-go-voting"
spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "backend-go-voting"